table FactSales
	lineageTag: 2280e175-9cf0-4024-a783-0f0104b9a364

	measure 'Total Sales' = SUM(FactSales[Sales])
		lineageTag: c2be2498-cb47-4c28-a9fc-f452f2ef6f04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = SUM(FactSales[Profit])
		lineageTag: ece4123f-b1b4-4cd8-9091-ecc54ee758f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders' = DISTINCTCOUNT(FactSales[Order ID])
		formatString: 0
		lineageTag: 85d5a4b6-d539-476e-857d-59f05bf95538

	measure 'Average Sales' = AVERAGE(FactSales[Sales])
		lineageTag: 3e11a332-80e1-4112-b006-2e3bf8b5d4f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Margin' = DIVIDE([Total Profit],[Total Sales])
		lineageTag: 58f38463-36b1-498f-abb2-76f8f0c720c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 73456498-5a1b-4ead-bedd-76c8195ca10a
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 4c5ed8dd-c1a1-49ee-89b1-5417a957a889
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: de4f7f98-fb29-4be3-9175-ce7c0053862e
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5cd2d848-eba0-4cb5-b5a6-e0394a6d72ff
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: c76484ef-fd1e-43ac-8f98-5d8a857f90c0
			defaultHierarchy: LocalDateTable_e2b58480-e389-4092-a2aa-64b9350f71b5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 6bdee2a1-74ff-48ca-9da7-8a43a7aa8ad6
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: ad08f21b-a4dc-4bfe-a0b6-6904fed58e2e
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: b7300447-8a49-4e47-97a1-24a6bde9e623
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 6d829dfc-2f20-48bc-a9fc-a366bdbabc6f
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: ea499a87-fe37-4510-a5ff-8fa33a01c518
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 71d2fe63-f0ec-44e2-a0e3-4c07a233fa9f
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 954b1cb1-ce48-4df7-b255-1c6d2a20aa25
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 9c6e4714-312e-4ece-9f81-d5aeb0ae561a
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b2cc4936-4a69-4124-911a-d1d816592454
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 591a759f-bec0-4f5b-8db8-8f586c9bb7a8
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: dd07e841-5219-45c2-b666-4a26d98a1a83
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 3ef2954c-3138-423b-9a8e-993734b8b54c
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: eea682f5-c066-4694-b957-c2c01644d121
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 956114fa-bebe-4722-babf-32317b600c7c
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 6a6ab9f7-4918-4bce-a97e-7389804669ef
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: ea5c41fa-93ed-466e-a649-b0d7b9f0a021
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 7ab2680b-cb48-4986-bc2d-07d92dad6650
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactSales = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\DELL\Desktop\ANALYSTS AFRICA\Sample - Superstore.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "Sample - Superstore", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}}, "en-US"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed column type",{{"Row ID", Int64.Type}, {"Order ID", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

